# Generated by Django 3.2.9 on 2021-12-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_products',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_names',
            field=models.CharField(max_length=5000),
        ),
    ]
