# Generated by Django 3.2.9 on 2021-11-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211130_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='home_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='province',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shipment_info',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='street',
        ),
    ]
